feat: add theme toggle
ory/summit-platform pull request #62
Opened 2023-08-10 15:01 UTC by LBBO

Only a draft until @ricardo-osorio-santos adds the sun rays to the SVG and I can animate them

2023-08-11 06:58 UTC, mszekiel commented
Video doesn't change immediately, do you know if we can fix it? Maybe we could switch to image first? Also the switcher animation is a bit off with not all elements animated same way and not hidden fully (se to transparent after hidden?).
![image](https://github.com/ory/summit-platform/assets/12242002/39d24f81-8a5b-4cb0-b9d6-aec32dfe649f)

2023-08-11 06:59 UTC, mszekiel commented
https://github.com/ory/summit-platform/assets/12242002/83c453e1-b151-4507-838e-b49037449985

2023-08-11 07:03 UTC, mszekiel commented on src/assets/icon/ThemeToggleIcon.css
For simplicity you can put it into svg into `<style>` so it's all together

2023-08-11 07:04 UTC, mszekiel requested changes

2023-08-11 07:04 UTC, mszekiel commented on src/assets/icon/ThemeToggleIcon.css
For simplicity you can put it into svg into <style> so it's all together

2023-08-11 07:05 UTC, mszekiel commented
Also IMO the animation is bit too fast, so you do not see it at all.

2023-08-11 08:57 UTC, jfcurran commented
from what i have seen this works very well - switching of elements is near instant. I agree that the animation is very fast, but its not bad. What's missing to get this shipped? good job

2023-08-16 07:32 UTC, LBBO commented
When a non-designer tackles a design issue 😂 

<img width="2547" alt="image" src="https://github.com/ory/summit-platform/assets/8076094/1a2f4bb6-6944-4776-88a1-70a63c18d0cb">

2023-08-16 09:24 UTC, LBBO commented
The image was already used as a fallback until the video finished loading. However, on slow connections, that could take a while. I've now added preload tags so the browser immediately loads both images, which actually seems to also be good for preventing LCP issues in #60. I'm a bit unsure if perhaps `prefetch` might be better here since one of the images isn't needed immediately and it could save 200KB during initial page load, but the other image is needed immediately and so I kept it as preload for the moment. WDYT?

2023-08-16 09:39 UTC, Benehiko approved these changes
Looks great!

2023-08-16 11:19 UTC, Benehiko approved these changes
LGTM

2023-08-16 11:21 UTC, merged